# fly.toml app configuration file generated for seedify-senior-backend-coding-exercise on 2025-01-14T23:17:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'seedify-senior-backend-coding-exercise'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
